export const TOOLBOX_COMPONENTS = [
  {
    name: "ArticleTitle",
    label: "ArticleTitle",
    category: "Misc",
    icon: "📦",
    defaultProps: {},
  },
  {
    name: "BgSection",
    label: "BgSection",
    category: "Misc",
    icon: "📦",
    defaultProps: {},
  },
  {
    name: "BottomCtaButton",
    label: "BottomCtaButton",
    category: "Misc",
    icon: "📦",
    defaultProps: {},
  },
  {
    name: "Button",
    label: "Button",
    category: "Misc",
    icon: "📦",
    defaultProps: {},
  },
  {
    name: "CardItem",
    label: "CardItem",
    category: "Misc",
    icon: "📦",
    defaultProps: {},
  },
  {
    name: "CardList",
    label: "CardList",
    category: "Misc",
    icon: "📦",
    defaultProps: {},
  },
  {
    name: "ComparisonTable",
    label: "ComparisonTable",
    category: "Misc",
    icon: "📦",
    defaultProps: {},
  },
  {
    name: "ComparisonTableHeader",
    label: "ComparisonTableHeader",
    category: "Misc",
    icon: "📦",
    defaultProps: {},
  },
  {
    name: "ComparisonTableRow",
    label: "ComparisonTableRow",
    category: "Misc",
    icon: "📦",
    defaultProps: {},
  },
  {
    name: "Container",
    label: "Container",
    category: "Misc",
    icon: "📦",
    defaultProps: {},
  },
  {
    name: "Footer",
    label: "Footer",
    category: "Misc",
    icon: "📦",
    defaultProps: {},
  },
  {
    name: "SectionTitle",
    label: "SectionTitle",
    category: "Misc",
    icon: "📦",
    defaultProps: {},
  },
  {
    name: "StoryItem",
    label: "StoryItem",
    category: "Misc",
    icon: "📦",
    defaultProps: {},
  },
  {
    name: "StoryList",
    label: "StoryList",
    category: "Misc",
    icon: "📦",
    defaultProps: {},
  },
  {
    name: "Text",
    label: "Text",
    category: "Misc",
    icon: "📦",
    defaultProps: {},
  },
  {
    name: "Video",
    label: "Video",
    category: "Misc",
    icon: "📦",
    defaultProps: {},
  },
];
